### ISSUE TITLE
Use TTF (Time To Final) as an OKR 

### ISSUE THREAD

**Issue by Willianvdv** [Hacker0x01/pingpong#17]
# Problem

Interest in ping pong is growing, with only one table there's more waiting than playing. 

![post-46711-12931137088547](https://user-images.githubusercontent.com/102915/36433862-de9177f6-165d-11e8-802b-5c62992558ba.jpg)
^ More players, more waiting time

# Solution

Increase the playing time by reducing the time from start to final. @mvgijssel told that in the Olympic version of round-the-table the TTF the go-to metric, let's use this proven concept to validate our existing rules and new rules

Thoughts?

**Comment by spidfire** [comment]
Any references? And I'm missing the explanations of the axis.  :neckbeard:

**Comment by martijnrusschen** [comment]
Idea: No more warnings. Doing a funny is out to avoid wasting time on that.

**Comment by Willianvdv** [comment]
@martijnrusschen let's focus on TTF first since it's a great idea.

**Comment by Willianvdv** [comment]
@spidfire see chapter 4.7 of the Roman sculptures, just after the recommended table size

**Comment by spidfire** [comment]
Are you sure your reference is correct? Because, as far as I know, it is the Greek architecture and art that is known for their curves, (look at temples for example) deforming the reality in such a way that it will look perfect to the human eye. Roman art is not only far less prestigious, but, for the most part, it merely copies the Greek. The only curvy thing they have is the archways in buildings. But those only work when supported by perfectly straight lines, which are surely missing here.
